import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:flutter/services.dart';

import '../../flavors.dart';
import '../monitoring/firebase_error_logger_service.dart';
import '../utils/util_functions.dart';
import 'firebase_messaging_service.dart';
import 'firebase_remote_config_service.dart';
import 'injection_container.config.dart';

/// The service locator. Resolve with `sl<T>()`; never construct a registered
/// type by hand.
///
/// Registration is generated by `injectable` into
/// `injection_container.config.dart` from annotations on the classes
/// themselves (`@lazySingleton`, `@injectable`, `@LazySingleton(as: …)`) and
/// from [RegisterModule] for third-party types. After adding or annotating a
/// class, run:
///
///   dart run build_runner build --delete-conflicting-outputs
final sl = GetIt.instance;

@InjectableInit()
Future<void> configureDependencies() => sl.init(environment: F.name);

Future<void> init() async {
  UtilFunctions.appLog("🚀 Starting of something great!");

  ///app flavor is late and need to be defined and is reused.
  F.appFlavor = Flavor.values.firstWhere(
    (element) => element.name == appFlavor,
  );

  // Flavor first: the generated init reads `F.baseUrl` / `F.name`.
  await Future.wait([F.initializeFirebaseApp(), configureDependencies()]);

  UtilFunctions.appLog("✅ All Main Services initialized");
}

/// Second stage, run from the splash screen once the first frame is up:
/// push notifications, crash reporting and remote config.
Future<void> splashInit() async {
  await Future.wait([
    MyFirebaseMessagingService.initNotifications(),
    FirebaseErrorLoggerService.to.init(),
    sl<FirebaseRemoteConfigService>().initialize(),
  ]);

  UtilFunctions.appLog("✅ All Services initialized");
}
